// Static product data - used when backend is not available
export const products = [
  {
    _id: "1",
    name: "Reclaimed Oak Dining Table",
    price: 134.99,
    category: "Tables",
    description: "A beautifully crafted dining table made from reclaimed oak wood. Each piece is unique with natural grain patterns and hand-finished edges.",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80",
    featured: true,
    special: false,
    popular: true,
    stock: 10,
    rating: 4.8,
  },
  {
    _id: "2",
    name: "Rustic Wooden Bench",
    price: 134.99,
    category: "Chairs",
    description: "Solid hardwood bench with a distressed finish. Perfect for entryways, dining rooms, or outdoor spaces.",
    image: "https://images.unsplash.com/photo-1549187774-b4e9b0445b41?w=400&q=80",
    featured: true,
    special: true,
    popular: false,
    stock: 15,
    rating: 4.6,
  },
  {
    _id: "3",
    name: "Handcrafted Wooden Chair",
    price: 134.99,
    category: "Chairs",
    description: "Elegant hand-carved wooden chair with smooth contours and durable construction. Ideal for any room.",
    image: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=400&q=80",
    featured: false,
    special: true,
    popular: true,
    stock: 8,
    rating: 4.5,
  },
  {
    _id: "4",
    name: "Walnut Bookcase",
    price: 134.99,
    category: "Bookcases",
    description: "Premium walnut wood bookcase with multiple adjustable shelves. A functional and stylish storage solution.",
    image: "https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&q=80",
    featured: true,
    special: false,
    popular: true,
    stock: 5,
    rating: 4.9,
  },
  {
    _id: "5",
    name: "Rustic Platform Bed Frame",
    price: 134.99,
    category: "Beds",
    description: "Low-profile platform bed frame made from solid reclaimed wood with a natural finish. Supports standard mattress sizes.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80",
    featured: false,
    special: true,
    popular: true,
    stock: 4,
    rating: 4.7,
  },
  {
    _id: "6",
    name: "Wooden Cabinet",
    price: 134.99,
    category: "Cabinets",
    description: "Spacious wooden cabinet with a natural wood grain finish. Features two large doors and interior shelving.",
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&q=80",
    featured: true,
    special: true,
    popular: false,
    stock: 7,
    rating: 4.4,
  },
  {
    _id: "7",
    name: "Oak Coffee Table",
    price: 134.99,
    category: "Tables",
    description: "Solid oak coffee table with a smooth top and tapered legs. Adds warmth and character to any living space.",
    image: "https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=400&q=80",
    featured: false,
    special: false,
    popular: true,
    stock: 12,
    rating: 4.3,
  },
  {
    _id: "8",
    name: "Decorative Wooden Box",
    price: 134.99,
    category: "Boxes",
    description: "Handcrafted decorative box with intricate wood inlay designs. Perfect for storing jewelry, letters, or keepsakes.",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&q=80",
    featured: true,
    special: false,
    popular: false,
    stock: 20,
    rating: 4.6,
  },
  {
    _id: "9",
    name: "Wooden Rocking Chair",
    price: 134.99,
    category: "Chairs",
    description: "Classic rocking chair crafted from solid maple. Smooth rocking motion and timeless design.",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&q=80",
    featured: false,
    special: true,
    popular: true,
    stock: 6,
    rating: 4.8,
  },
  {
    _id: "10",
    name: "Reclaimed Wood Shelf",
    price: 134.99,
    category: "Bookcases",
    description: "Floating wall shelf made from reclaimed barn wood. Unique character marks and weathered finish included.",
    image: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=400&q=80",
    featured: true,
    special: true,
    popular: false,
    stock: 9,
    rating: 4.5,
  },
  {
    _id: "11",
    name: "Bamboo Storage Box",
    price: 134.99,
    category: "Boxes",
    description: "Eco-friendly bamboo storage box with a magnetic closure lid. Lightweight and durable for everyday use.",
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&q=80",
    featured: false,
    special: false,
    popular: true,
    stock: 25,
    rating: 4.2,
  },
  {
    _id: "12",
    name: "Heritage Wooden Dresser",
    price: 134.99,
    category: "Cabinets",
    description: "Six-drawer dresser with solid wood construction and antique brass hardware. Generous storage in a classic silhouette.",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80",
    featured: true,
    special: false,
    popular: true,
    stock: 3,
    rating: 4.9,
  },
];

export const categories = ["All", "Tables", "Chairs", "Beds", "Bookcases", "Cabinets", "Boxes"];
